import { NextResponse } from 'next/server'
import { agentsV2Url, foundryHeaders } from '../../../../helpers'

/**
 * GET /api/foundry/containers/[containerId]/files/[fileId]
 *
 * Proxy for downloading files generated by Code Interpreter.
 * Fetches binary content from:
 *   {endpoint}/openai/containers/{containerId}/files/{fileId}/content?api-version=2025-11-15-preview
 *
 * Returns the raw binary data with appropriate Content-Type and Content-Disposition headers
 * so the browser can display images inline or trigger file downloads.
 */
export async function GET(
  request: Request,
  { params }: { params: { containerId: string; fileId: string } }
) {
  try {
    const { containerId, fileId } = params

    if (!containerId || !fileId) {
      return NextResponse.json(
        { error: 'containerId and fileId are required' },
        { status: 400 }
      )
    }

    // Extract optional filename from query params for Content-Disposition
    const url = new URL(request.url)
    const filename = url.searchParams.get('filename') || fileId

    const headers = await foundryHeaders()

    // Fetch the file content from the Foundry containers API
    const endpoint = process.env.FOUNDRY_PROJECT_ENDPOINT?.replace(/\/+$/, '')
    if (!endpoint) {
      return NextResponse.json(
        { error: 'FOUNDRY_PROJECT_ENDPOINT not configured' },
        { status: 500 }
      )
    }

    const fileUrl = `${endpoint}/openai/containers/${encodeURIComponent(containerId)}/files/${encodeURIComponent(fileId)}/content?api-version=2025-11-15-preview`

    console.log(`[containers] Fetching file: ${fileUrl}`)

    const response = await fetch(fileUrl, {
      method: 'GET',
      headers: {
        Authorization: headers.Authorization,
      },
    })

    if (!response.ok) {
      const errText = await response.text().catch(() => '')
      console.error(`[containers] File fetch failed: ${response.status}`, errText)
      return NextResponse.json(
        { error: `Failed to fetch file (${response.status})`, details: errText },
        { status: response.status }
      )
    }

    // Get the response as an ArrayBuffer
    const buffer = await response.arrayBuffer()

    // Determine content type from filename extension
    const ext = filename.split('.').pop()?.toLowerCase() || ''
    const contentTypeMap: Record<string, string> = {
      png: 'image/png',
      jpg: 'image/jpeg',
      jpeg: 'image/jpeg',
      gif: 'image/gif',
      svg: 'image/svg+xml',
      pdf: 'application/pdf',
      csv: 'text/csv',
      json: 'application/json',
      txt: 'text/plain',
      py: 'text/x-python',
      html: 'text/html',
      xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      zip: 'application/zip',
    }
    const contentType = contentTypeMap[ext] || response.headers.get('content-type') || 'application/octet-stream'

    // For images and HTML, allow inline display; for other files, trigger download
    const isImage = contentType.startsWith('image/')
    const isHtml = contentType === 'text/html'
    const disposition = (isImage || isHtml)
      ? `inline; filename="${filename}"`
      : `attachment; filename="${filename}"`

    console.log(`[containers] Serving file: ${filename} (${contentType}, ${buffer.byteLength} bytes)`)

    return new Response(buffer, {
      status: 200,
      headers: {
        'Content-Type': contentType,
        'Content-Disposition': disposition,
        'Content-Length': String(buffer.byteLength),
        'Cache-Control': 'private, max-age=3600',
      },
    })
  } catch (error) {
    console.error('[containers] Error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Internal server error' },
      { status: 500 }
    )
  }
}
